version: '3'
services:
  postgres_database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: iluvcoffee
      POSTGRES_PASSWORD: iluvcoffee_pass123
  postgres_admin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@iluvcoffee.com
      PGADMIN_DEFAULT_PASSWORD: iluvcoffee_pass123
